### ISSUE TITLE
Research improved interpolation method

### ISSUE THREAD

**Issue by lexvand** [nens/threedidepth#7]
- Propose a name for the new method ;-)
- Review original code
- Time (calculation step) dependence:
  - Identify
  - Assess effort and result of getting rid of them
- Threedidepth:
  - Get the PR to work again
  - Compare performance to other calculators (constant, delaunay)
  - Compare results part I (part II will be after elimination of time dependence):
    - In issues with changing triangle layouts
    - With high resolution results
  - Estimate removing time dependence in threedidepth
  - Estimate implementing & removing time dependence in Lizard

**Comment by arjanverkerk** [comment]
Some preliminary conclusions on removing time dependence:
- No timestep in EVA/threedidepth code:
  - Bad for performnce, would need to inspect all timesteps always
  - Defeats (part of) purpose of including simulation info
- Efficient interpolation in Lizard (no timestep dependence) will be difficult:
  - Custom squares / triangles
  - Custom combined bilinear & barylinear interpolation instead of barycentric

So, that seems not good news, but I have prepared a proposal for yet another approach. More to follow soon.

**Comment by arjanverkerk** [comment]
Here is my proposal:

https://docs.google.com/document/d/11wISz6EeM2QJZa0ceRadK0i8ZAIugbyTC8tAm8drOMY/edit?usp=sharing

And the summary:

It is proposed to use bilinear interpolation on calculation cells instead of triangulation schemes. Simple rules are defined for the values at the corners in such a way that a consistent interpolated value is defined that is continuous across all wet cell boundaries.
